# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/ADS_do/lab5/ads_lab5_project_do/ads_lab5_project_do.srcs/sources_1/bd/lab5_bd/ip/lab5_bd_axi_gpio_0_0/lab5_bd_axi_gpio_0_0.xci
# IP: The module: 'lab5_bd_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/ADS_do/lab5/ads_lab5_project_do/ads_lab5_project_do.gen/sources_1/bd/lab5_bd/ip/lab5_bd_axi_gpio_0_0/lab5_bd_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab5_bd_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/ADS_do/lab5/ads_lab5_project_do/ads_lab5_project_do.gen/sources_1/bd/lab5_bd/ip/lab5_bd_axi_gpio_0_0/lab5_bd_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab5_bd_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/ADS_do/lab5/ads_lab5_project_do/ads_lab5_project_do.gen/sources_1/bd/lab5_bd/ip/lab5_bd_axi_gpio_0_0/lab5_bd_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab5_bd_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/ADS_do/lab5/ads_lab5_project_do/ads_lab5_project_do.srcs/sources_1/bd/lab5_bd/ip/lab5_bd_axi_gpio_0_0/lab5_bd_axi_gpio_0_0.xci
# IP: The module: 'lab5_bd_axi_gpio_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/ADS_do/lab5/ads_lab5_project_do/ads_lab5_project_do.gen/sources_1/bd/lab5_bd/ip/lab5_bd_axi_gpio_0_0/lab5_bd_axi_gpio_0_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab5_bd_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/ADS_do/lab5/ads_lab5_project_do/ads_lab5_project_do.gen/sources_1/bd/lab5_bd/ip/lab5_bd_axi_gpio_0_0/lab5_bd_axi_gpio_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab5_bd_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/ADS_do/lab5/ads_lab5_project_do/ads_lab5_project_do.gen/sources_1/bd/lab5_bd/ip/lab5_bd_axi_gpio_0_0/lab5_bd_axi_gpio_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab5_bd_axi_gpio_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
