# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/ads_lab5_project_do/ads_lab5_project_do.srcs/sources_1/bd/lab5_bd/ip/lab5_bd_gen_fun_top_0_1/lab5_bd_gen_fun_top_0_1.xci
# IP: The module: 'lab5_bd_gen_fun_top_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/ads_lab5_project_do/ads_lab5_project_do.gen/sources_1/bd/lab5_bd/ip/lab5_bd_gen_fun_top_0_1/src/sin10K/sin10K.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sin10K || ORIG_REF_NAME==sin10K} -quiet] -quiet

# XDC: c:/ads_lab5_project_do/ads_lab5_project_do.gen/sources_1/bd/lab5_bd/ip/lab5_bd_gen_fun_top_0_1/src/test_gen_fun.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab5_bd_gen_fun_top_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/ads_lab5_project_do/ads_lab5_project_do.srcs/sources_1/bd/lab5_bd/ip/lab5_bd_gen_fun_top_0_1/lab5_bd_gen_fun_top_0_1.xci
# IP: The module: 'lab5_bd_gen_fun_top_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/ads_lab5_project_do/ads_lab5_project_do.gen/sources_1/bd/lab5_bd/ip/lab5_bd_gen_fun_top_0_1/src/sin10K/sin10K.xci
#dup# set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==sin10K || ORIG_REF_NAME==sin10K} -quiet] -quiet

# XDC: c:/ads_lab5_project_do/ads_lab5_project_do.gen/sources_1/bd/lab5_bd/ip/lab5_bd_gen_fun_top_0_1/src/test_gen_fun.xdc
# XDC: The top module name and the constraint reference have the same name: 'lab5_bd_gen_fun_top_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
