# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param synth.incrementalSynthesisCache C:/Users/Pau/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-12676-PAUPC1/incrSyn
set_param xicom.use_bs_reader 1
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/ads_lab5_tests_do/ads_lab5_tests_do.cache/wt [current_project]
set_property parent.project_path C:/ads_lab5_tests_do/ads_lab5_tests_do.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property ip_output_repo c:/ads_lab5_tests_do/ads_lab5_tests_do.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/ADS_do/lab5/src/ads_driver.vhd
  C:/ADS_do/lab5/src/cross_generator.vhd
  C:/ADS_do/lab5/src/daq_top_do.vhd
  C:/ADS_do/lab5/src/daq_trigger_controller.vhd
  C:/ADS_do/lab5/src/gen_fun.vhd
  C:/ADS_do/lab5/src/o_generic_sr.vhd
  C:/ADS_do/lab5/src/sync_ram_dualport.vhd
  C:/ADS_do/lab5/src/vga_port_test.vhd
  C:/ADS_do/lab5/src/vga_sync_gen.vhd
  C:/ADS_do/lab5/src/virtual_dac.vhd
  C:/ADS_do/lab5/src/daq_n4_hw_test.vhd
}
add_files C:/ADS_do/lab5/src/daq_clk_adapter/daq_clk_adapter.bd
set_property used_in_implementation false [get_files -all c:/ADS_do/lab5/src/daq_clk_adapter/ip/daq_clk_adapter_clk_wiz_0_0/daq_clk_adapter_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/ADS_do/lab5/src/daq_clk_adapter/ip/daq_clk_adapter_clk_wiz_0_0/daq_clk_adapter_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/ADS_do/lab5/src/daq_clk_adapter/ip/daq_clk_adapter_clk_wiz_0_0/daq_clk_adapter_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/ADS_do/lab5/src/daq_clk_adapter/daq_clk_adapter_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/ADS_do/lab5/xdc/nexys4.xdc
set_property used_in_implementation false [get_files C:/ADS_do/lab5/xdc/nexys4.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top daq_n4_hw_test -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef daq_n4_hw_test.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file daq_n4_hw_test_utilization_synth.rpt -pb daq_n4_hw_test_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
