# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/ADS_do/lab5/xdc/nexys4.xdc

# Block Designs: C:/ADS_do/lab5/src/daq_clk_adapter/daq_clk_adapter.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==daq_clk_adapter || ORIG_REF_NAME==daq_clk_adapter} -quiet] -quiet

# IP: C:/ADS_do/lab5/src/daq_clk_adapter/ip/daq_clk_adapter_clk_wiz_0_0/daq_clk_adapter_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==daq_clk_adapter_clk_wiz_0_0 || ORIG_REF_NAME==daq_clk_adapter_clk_wiz_0_0} -quiet] -quiet

# XDC: C:/ADS_do/lab5/src/daq_clk_adapter/daq_clk_adapter_ooc.xdc
