# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/xdc/lab5_dac.xdc

# Block Designs: bd/lab5_bd/lab5_bd.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab5_bd || ORIG_REF_NAME==lab5_bd} -quiet] -quiet

# IP: bd/lab5_bd/ip/lab5_bd_processing_system7_0_0/lab5_bd_processing_system7_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab5_bd_processing_system7_0_0 || ORIG_REF_NAME==lab5_bd_processing_system7_0_0} -quiet] -quiet

# IP: bd/lab5_bd/ip/lab5_bd_rst_ps7_0_100M_0/lab5_bd_rst_ps7_0_100M_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab5_bd_rst_ps7_0_100M_0 || ORIG_REF_NAME==lab5_bd_rst_ps7_0_100M_0} -quiet] -quiet

# IP: bd/lab5_bd/ip/lab5_bd_lab5_axi_do_0_0/lab5_bd_lab5_axi_do_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab5_bd_lab5_axi_do_0_0 || ORIG_REF_NAME==lab5_bd_lab5_axi_do_0_0} -quiet] -quiet

# IP: bd/lab5_bd/ip/lab5_bd_auto_pc_0/lab5_bd_auto_pc_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab5_bd_auto_pc_0 || ORIG_REF_NAME==lab5_bd_auto_pc_0} -quiet] -quiet

# IP: bd/lab5_bd/ip/lab5_bd_ps7_0_axi_periph_0/lab5_bd_ps7_0_axi_periph_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab5_bd_ps7_0_axi_periph_0 || ORIG_REF_NAME==lab5_bd_ps7_0_axi_periph_0} -quiet] -quiet

# IP: bd/lab5_bd/ip/lab5_bd_gen_fun_top_0_1/lab5_bd_gen_fun_top_0_1.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==lab5_bd_gen_fun_top_0_1 || ORIG_REF_NAME==lab5_bd_gen_fun_top_0_1} -quiet] -quiet

# XDC: c:/Users/pixi4/UNI/ADS/ADS_lab/lab5/ads_lab5_project_do/ads_lab5_project_do.gen/sources_1/bd/lab5_bd/lab5_bd_ooc.xdc
